services:
  testdb:
    image: docker.io/postgres:14.8-alpine3.18
    restart: always
    container_name: test_db_container
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d
